#!/bin/bash

TOOLS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$TOOLS_ROOT/../" && mvn test-compile org.pitest:pitest-maven:mutationCoverage && cd target/pit-reports/ && python3 -m http.server